name: Deploy to Firebase Hosting on merge
# For testing purposes
on: push
# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: "12.x"
#       - uses: subosito/flutter-action@v1
#         with:
#           flutter-version: "2.0.5"
#       - run: flutter pub get
#       - run: flutter build web
#       - uses: actions/checkout@v2
#       - uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: "${{ secrets.GITHUB_TOKEN }}"
#           firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
#           channelId: live
#           projectId: polyapp-d3d40

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.5"
      - run: flutter pub get
      - run: flutter build web
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
