name: Flutter Android Build

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 17
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          flutter-version: "2.2.2"
      - run: flutter pub get
      # Flutter test breaks, as we currently do not test ❤️
      # - run: flutter test

      # Compile and test the production apk on merges to main
      - run: flutter build apk --debug --flavor productive -t lib/main.dart
        if: github.base_ref == 'refs/heads/main'
      # Compile and test the development apk on merges that are not on main
      - run: flutter build apk --debug --flavor development -t lib/main_dev.dart
        if: github.base_ref != 'refs/heads/main'

      # Build the production version on merges that are to main
      - run: flutter build appbundle --debug --flavor productive -t lib/main.dart
        if: github.base_ref == 'refs/heads/main'
      # Build the development version on merges that are not to main
      - run: flutter build appbundle --debug --flavor development -t lib/main_dev.dart
        if: github.base_ref != 'refs/heads/main'
